name: Verificacion del Proyecto
on: [push, pull_request] # Se activa solo al subir cambios o crear PR

jobs:
  revisar-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Simular Revision
        run: |
          echo "Revisando que el index.html exista..."
          ls index.html
          echo "¡Todo listo! El proyecto de Registro de Alumnos es valido."
